# Generated by Django 3.2 on 2022-07-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220728_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ManyToManyField(blank=True, to='users.City'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ManyToManyField(blank=True, to='users.Country'),
        ),
    ]
