# Generated by Django 3.2 on 2022-07-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20220728_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
