# Generated by Django 3.2 on 2022-07-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='products',
            new_name='product',
        ),
    ]
